name: Test
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  test:
    name: This is a test
    if: github.event.base_ref == 'refs/heads/master' && startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - run: echo "ref=${{ github.ref }}"
      - run: echo "rer_name=${{ github.ref_name }}"
      - run: echo "sender.name=${{ github.event.sender.name }}"
      - run: echo "${{ github.event.base_ref }}"
      - run: echo "${{ github.event.ref }}"
      - run: echo "${{ github.base_ref }}"
      - run: echo $GITHUB_REF
      - run: BRANCH_NAME=${GITHUB_REF#refs/heads/} && echo $BRANCH_NAME
      - run: echo "by ${{ github.event.head_commit.author.username }}"
