name: Create Release Tag
run-name: Create release tag for ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [master]
    types: [closed]
env:
  package_dir: ./
  example_dir: ./example
jobs:
  validation:
    name: Release validation
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release tag
        working-directory: ${{ env.package_dir }}
        run: >
          TAG=$(cat pubspec.yaml | grep version | sed 's/version:\s*//' | xargs echo) &&
          git fetch origin master &&
          git checkout master &&
          git tag $(echo "v$TAG") &&
          git push origin $(echo "v$TAG")
